### ISSUE TITLE
complexHub.invoke ---> fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by pwr7549** [adamhartford/SwiftR#8] opened 2015-08-29 00:55 UTC
I tried to follow your ways of writing in that page also I tried to applied without :[String, AnyObject] to this message or with it.. I tried with many various possible to assign this. I always end up with this same fatal error like this.. 

fatal error: unexpectedly found nil while unwrapping an Optional value

func adamsWay() {
        SwiftR.connect("http://neverland.com:8080/configserver/signalr/hubs") { [weak self] connection in
            self?.complexHub = connection.createHubProxy("lPConfigServer")
            
            self?.complexHub.on("getNewOnlineUser") { args in
                let m: AnyObject = args!["0"] as AnyObject!
                println(m)
            }
        }
        
        let message: [String: AnyObject] = [
            "messageId": 1,
            "message": "Complex Test",
            "detail": "This is a complex message",
            "items": ["foo", "bar", "baz"]
        ]

       // Invoke server method
        complexHub.invoke("getConnected", arguments: [message])  <<<< Something is going on with issue of [AnyObject]? here within that argument part.. Any suggest to resolve that? 
    }

**Comment by adamhartford** [comment] 2015-08-29 02:19
`complexHub` is nil because the SignalR connection hasn't happened yet. Notice that `complexHub` is assigned in the `SwiftR.connect` callback. Perhaps I can make some changes that make it easier to be aware of the connection state.

Basically, you need to wait to call `invoke` until you're connected.

**Comment by pwr7549** [comment] 2015-08-29 14:51
That would be more helpful to build a new connection state in that source. How do I make it to wait until it is connected to the server?

**Comment by adamhartford** [comment] 2015-08-29 20:11
It all depends on how you want your app to work. But you normally wouldn't call `invoke` immediately after `connect`. There is a `connected` event/callback though. You could write your routine like this and it would work. This calls `invoke` as soon as the SignalR connection is made:

```swift
   func adamsWay() {
        SwiftR.connect("http://myserver.com:8080") { [weak self] connection in
            self?.complexHub = connection.createHubProxy("complexHub")
            
            self?.complexHub.on("notifyComplex") { args in
                let m: AnyObject = args!["0"] as AnyObject!
                print(m)
            }

            connection.connected = {
                let message: [String: AnyObject] = [
                    "messageId": 1,
                    "message": "Complex Test",
                    "detail": "This is a complex message",
                    "items": ["foo", "bar", "baz"]
                ]
                
                // Invoke server method
                self?.complexHub.invoke("sendComplex", arguments: [message])
            }
        }
    }
```

**Comment by pwr7549** [comment] 2015-08-31 17:00
Hello Adam,

There is some disturbances here in this coding, if I create a typo of URL Address or misnamed the Hub Proxy, it does not complain anything! None of the Events Exposes to create some tattle tales.. In Error Handling, it just said the error is nil. Sounds strange. If I use Persistent Connection Test, it crashed due to nil found issue.. 

There is something going on with this one, any familiar with this common problem? 

Regards,
Patrick Reece

**Comment by adamhartford** [comment] 2015-08-31 17:18
If I update that code above to use a bad URL, I can see an error:

```swift
connection.error = { error in
    print(error) // Swift 2... use println for Swift 1
}

/**
Prints:

Optional({
    readyState = 0;
    status = 0;
    statusText = error;
})
*/
```

Are you using my sample SignalR server project as an example? If not, how did you configure your persistent connection?

However, I do need to improve the error handling if you enter a bad hubName. It currently shouldn't crash, but nothing will happen.

If you're having trouble getting anything to work, it would help to post your SignalR server code.

**Comment by pwr7549** [comment] 2015-08-31 20:11
Hello Adam, 

I just inserted  this  error part as show below

            connection.error = {
                error in
                
                println("error: \(error)")
            }
into the connection.connected = { ….. } part.. It works fine and it repeats in every approximately five seconds I misspelled the URL address in that SwiftR.connect or/and misnamed the Hub Proxy. It will show the status of 500 and 404 if I misspelled them.  And what we should do with this func errorHandling() {………} and it does not do tattletale at all. 

I would expect to receive some  tattletales, if I misspelled the invoke server method or threw the bad parameters into it, but it did not. The Events Handler does not display anything, after throwing good or bad parameters into the invoke server method, too.    

I believed if I throw the misspelled or wrong URL address into persistent connection method. It will crash and complain about nil issue.. The question is that where do I find the place of URL address that is applied to this method. ? SignalR is running on Microsoft IIS server. 


I realized that this server does not have the persistent connection after looking for these files. None of these files are found in comparing to your examples.. If I tried many different URL, it always crash with the same complain about nil found issue... It was placed right after self?.complexHub.on (…){…}.  Is there any advise for using this one? Where should I find a file in that server to find the right URL address for this one? Is it an option one? 

Patric kReece

**Comment by adamhartford** [comment] 2015-09-01 00:36
Are you using SignalR clients on any platforms other than iOS or Mac? The JavaScript client in a web application maybe? It would be helpful if you can demonstrate the behavior you're looking for in one of those clients. It would prove that your server is working correctly, and help me understand the behavior you're looking for in SwiftR.

I have examples of hubs, persistent connections, and the JavaScript client (if it helps) at: https://github.com/adamhartford/SignalRDemo

Could you possibly post more client/server code and point out where you're having a problem?

**Comment by pwr7549** [comment] 2015-09-01 01:41
This is Server Side here.........
namespace MonkeyServer
{
    /// <summary>
    /// SignalR Server : Complete Server for Video Conferencing, JavaScript Client and iOS client access it control Monkey call operations.
    /// </summary>
    public class MonkeyServer: Hub 
    {
        /// <summary>
        /// All online users dictionary
        /// </summary>
        public static ConcurrentDictionary<string, User> Users = new ConcurrentDictionary<string, User>();
        /// <summary>
        /// All online Connections array
        /// </summary>
        public static Connections connections = new Connections();

        public User GetConnected(string username, string usertype, string loginid, string entityIDOfCallingInterpreter, string REMOTE_ADDR, string timeZone, string usercreationdatetime, string userregistrationstatus, int freeSessions, bool reconnect)
        {

            return GetConnectedInternal(username, usertype, loginid, entityIDOfCallingInterpreter, REMOTE_ADDR, timeZone, usercreationdatetime, userregistrationstatus, freeSessions, false, reconnect,false);
        }
    
        
/// <summary>
/// Login in signalr and database user login event will be registered
/// </summary>
/// <param name="username"></param>
/// <param name="usertype"></param>
/// <param name="loginid"></param>
/// <param name="entityIDOfCallingInterpreter"></param>
/// <param name="REMOTE_ADDR"></param>
/// <param name="timeZone"></param>
/// <param name="usercreationdatetime"></param>
/// <param name="userregistrationstatus"></param>
/// <param name="freeSessions"></param>
/// <returns></returns>
public User GetConnected(string username, string usertype, string loginid, string entityIDOfCallingInterpreter,string REMOTE_ADDR, string timeZone, string  usercreationdatetime, string userregistrationstatus, int freeSessions)
        {a
            
            return GetConnectedInternal(username, usertype, loginid, entityIDOfCallingInterpreter, REMOTE_ADDR, timeZone, usercreationdatetime, userregistrationstatus, freeSessions, false, false, true);
            }

/// <summary>
/// Old connect method 
/// </summary>
/// <param name="username"></param>
/// <param name="usertype"></param>
/// <param name="loginid"></param>
/// <param name="entityIDOfCallingInterpreter"></param>
/// <param name="REMOTE_ADDR"></param>
/// <returns></returns>
public User GetConnected(string username, string usertype, string loginid, string entityIDOfCallingInterpreter, string REMOTE_ADDR)
{
    return GetConnectedInternal(username, usertype, loginid, entityIDOfCallingInterpreter, REMOTE_ADDR, "0", DateTime.Now.ToString(),"", 0, true,false, true);
}

/// <summary>
/// This function is responsible to connect a new user to SignalR Server, It logs Login log entry in event log table. It provides the current user list of all available users and let other users know entry of a new user. It also create opentok session for a new user., 
/// </summary>
/// <param name="username"></param>
/// <param name="usertype"></param>
/// <param name="loginid"></param>
/// <param name="entityIDOfCallingInterpreter"></param>
/// <param name="REMOTE_ADDR"></param>
/// <param name="timeZone"></param>
/// <param name="usercreationdatetime"></param>
/// <param name="userregistrationstatus"></param>
/// <param name="freeSessions"></param>
/// <param name="IsBackward"></param>
/// <returns></returns>
/// 
private User GetConnectedInternal(string username, string usertype, string loginid, string entityIDOfCallingInterpreter, string REMOTE_ADDR, string timeZone, string usercreationdatetime, string userregistrationstatus, int freeSessions, bool IsBackward, bool reconnect=false, bool OLD_IOSVerison=false)
{  
    User user=new User();
    try
    {
        UserType Usertype = helper.ParseEnum<UserType>(usertype);
        D2D d2d = new D2D();
        connections.Add(Context.ConnectionId);

        EventLogUserDetails userdetail = new EventLogUserDetails();
        EventLog eventlog = new EventLog();
        eventlog.EventType = EventType.User_Login;
        eventlog.InitiatorID = long.Parse(loginid);
        eventlog.InitiatorType = Usertype;
        eventlog.InitiatorName = username;
         if (reconnect )
        userdetail.UserLogin = EventsLogWrraper.GetEvent(eventlog);
         else
        userdetail.UserLogin = EventsLogWrraper.GetEventStart(eventlog);
        Opentok opentok = OpentokWrapper.getOpentok(Context.ConnectionId, REMOTE_ADDR);

        user = new User(username, helper.ParseEnum<UserType>(usertype), Context.ConnectionId.ToString(), opentok, loginid, entityIDOfCallingInterpreter, userdetail, int.Parse(timeZone), DateTime.Parse(usercreationdatetime), userregistrationstatus, freeSessions, IsBackward );

        Users.TryAdd(Context.ConnectionId, user);
        Clients.Clients(connections.AllExcept(Context.ConnectionId)).getNewOnlineUser(user);
        if (OLD_IOSVerison )
                  Clients.Client(Context.ConnectionId).getOnlineUsers(Users, d2d);
        else
             Clients.Client(Context.ConnectionId).getOnlineUsers(Users, d2d, reconnect );
       
        ExceptionalManager.WriteInfo("User Successfully connected to SignalR - UserName :" + username + "| Reconnected : " + reconnect + "| User type :" + Usertype + "| ConnectionId : " + Context.ConnectionId + "| Logid:" + loginid + "| Opentok Appkey:" + opentok.ApiKey + "| Opentok SessionId:" + opentok.SessionId + "| Opentok TokenID:" + opentok.Token , "GetConnected", GetFileName()); 

    }

   

    catch (Exception exp)
    { ExceptionalManager.LogError(user, exp);  }
    return user;
}

**Comment by pwr7549** [comment] 2015-09-01 02:30
I just only use this coding on iOS app.. I have not tried on any other than this one.. I am working for a company it has been running for web based app and previous iOS version app.. This company wants me to finish up the codings after the previous developer was dismissed. He used SignalR-ObjC  coding in that app. It is not working, he did not finished it entirely. So I migrated them into Swift and put your SwiftR into this app instead. 

Patrick R.

**Comment by adamhartford** [comment] 2015-09-01 03:35
Thanks, this helps. Short answer: When you're passing an array, not a dictionary, pass everything as a string:

```swift
let localArgumentsArray = [
   self!.helpUserName(),
   usertype,
   loginid,
   "0",
   "75.128.190.100",
   self!.localTimeZoneOffset(), // Assuming this is a string
   self!.dateAndTimeStamp(), // Assuming this is a string
   "Help",
   "0" // This is the necessary change
]
```

Or...

Modify your hub so that `GetConnected(param1, param2, param3 ... paramN)` accepts a single object like `GetConnected(ConnectionParams params)`. Then you'll pass a dictionary instead of an array and everything will work.

I think I need to make some changes to my serialization routine for it to work as you originally wrote it, but I believe either of the above changes will work for you.

**Comment by pwr7549** [comment] 2015-09-01 05:14
I set all strings in that array and threw it into arguments of invoke method.. No change  or any significant results.. 

I can’t change the hub server because it will impacts the rest of other clients the other developers worked on them in the past. Right now, that server is their big money generating server.. Can’t afford to get this server abrupt off at this time. The company team will work it out in next plans. I am being pressed to get it done working properly. However, I would like to have some change on your serialization routine by you. It will help us a lot.

**Comment by adamhartford** [comment] 2015-09-01 12:47
I used the exact client/server methods you had and could reproduce a JSON serialization error. Passing an array of strings worked. Does no change mean it still crashes, or reaches your server but not the Swift callback?

**Comment by pwr7549** [comment] 2015-09-01 21:50
Hello Adam, 

I tried to reproduce these codings to show you the result as shown below here.. 


I tried to test to see the result of that coding, when I put the invoke server method outside of connection.connected block. I would expect to see a crash like this coding, but it did not. I am not sure why. I will have to fiddling them around to find a reason of causing a crash.  Please see the output as a result after this snippet of coding. 

func adamsWay2() {
        SwiftR.connect("http://monkey.com:8080/configserver/signalr/hubs") { [weak self] connection in
            self?.complexHub = connection.createHubProxy(“MonkeyServer")
            
            self?.complexHub.on("getNewOnlineUser") { args in
                println("results: \(args!)”) \\ I hope I could see something further than just specific with index reference of Array.. 
                let m: AnyObject = args!["0"] as AnyObject!
                let n: AnyObject = args!["1"] as AnyObject!
                println("Hub Result: \(m)")
                println("Hub Result1: \(n)")
            }
            connection.connected = {
            }          
            let usertype: String = "Deafuser"
            let loginid: String = "0"
            let membershipNumber: String = "82778277"
            let membershipPassword: String = "12345678"
            
            let localArgumentsArray = [
                self!.helpUserName(), \\ Yes it is in String
                usertype,
                loginid,
                "0",
                "75.128.190.152",
                self!.localTimeZoneOffset(), \\ Yes it is in String
                self!.dateAndTimeStamp(),  \\ Yes it is in String
                "Help",
                "0"
            ]
            println("Args: \(localArgumentsArray)")
         
            // Invoke server method 
            self?.complexHub.invoke("getConnected", arguments: localArgumentsArray)
            
            connection.received = {
                received in
                println("received: \(received)")
            }
            connection.error = {
                error in
                
                println("error: \(error)")
            }
        }
    }

The output  from the Debug Area  as shown below here for first attempt of this coding.

args in Deaf User Login: Optional([F62E8401DB294BEBA4D2318E9EFBE9C8, -4, 09-01-2015 06:07:39Z, 82778277, 12345678])
Args: [Help-33267, Deafuser, 0, 0, 75.128.190.152, -4, 09-01-2015 06:07:39Z, Help, 0]
received from Events Expose Function: nil 
error from Error Handling Function: nil
No error exists..
error: nil



I put another attempt of coding here as shown below.. I leave these variables  above of and outside of connection.connected block, but I leave the invoke server method inside of that block. So we can see the output of arguments that had fed it into the invoke server method. 

    func adamsWay2() {
        SwiftR.connect("http://monkey.com:8080/configserver/signalr/hubs") { [weak self] connection in
            self?.complexHub = connection.createHubProxy(“MonkeyServer")
            
            self?.complexHub.on("getNewOnlineUser") { args in
                println("results: \(args!)")
                let m: AnyObject = args!["0"] as AnyObject!
                let n: AnyObject = args!["1"] as AnyObject!
                println("Hub Result: \(m)")
                println("Hub Result1: \(n)")
            }
            
            let usertype: String = "Deafuser"
            let loginid: String = "0"
            let membershipNumber: String = "82778277"
            let membershipPassword: String = "12345678"
            
            let localArgumentsArray = [
                self!.helpUserName(),
                usertype,
                loginid,
                "0",
                "75.128.190.152",
                self!.localTimeZoneOffset(),
                self!.dateAndTimeStamp(),
                "Help",
                "0"
            ]
            println("Args: \(localArgumentsArray)")
 
            connection.connected = {
                
                // Invoke server method
                
                self?.complexHub.invoke("getConnected", arguments: localArgumentsArray)
                
            }

            connection.received = {
                received in
                println("received: \(received)")
            }
            connection.error = {
                error in
                
                println("error: \(error)")
            }
        }
    }

Here this output from Debug Area as show below

args in Deaf User Login: Optional([22F32A379B2C438896C3D96F53EE42F4, -4, 09-01-2015 15:16:44Z, 82778277, 12345678])
received from Events Expose Function: nil 
Args: [Help-60035, Deafuser, 0, 0, 75.128.190.152, -4, 09-01-2015 15:16:44Z, Help, 0]
error from Error Handling Function: nil
No error exists..


Patrick Reece 

P.S. I was not able to use the internet, it was knocked down for many hours. Now I am able to resume working through Internet! Sorry for long waiting to respond back to you..

**Comment by pwr7549** [comment] 2015-09-02 16:15
I used Charles to trace some information and it showed that ConnectionId is already given but  in my debug area, it does not receive any ConnectionID. Is there something that I am overlooked? 

func adamsWay2() {
        let appVersion = NSBundle.mainBundle().infoDictionary?["CFBundleShortVersionString"] as! String
        let args = [appVersion]
        SwiftR.connect("http:/monkey.com:8080/configserver/signalr/hubs") { [weak self] connection in
            self?.complexHub = connection.createHubProxy(“MonkeyServer")
            
            connection.connected = {
                
                // Invoke server method
                
                self?.complexHub.invoke("getSettings", arguments: args)
                println("connection ID: \(connection.connectionID)")
            }
            
            
            connection.received = {
                received in
                println("received: \(received)")
                println("connection ID: \(connection.connectionID)")
            }
            connection.error = {
                error in
                println("connection ID: \(connection.connectionID)")
                println("error: \(error)")
            }
            println("connection ID: \(connection.connectionID)")
        }
    }



Response found in Charles as shown below 
{
	"Url": "/ConfigServer/signalr/hubs/signalr",
	"ConnectionToken": "o9YOKpOzye5gdLOYeaPo+vshVwk0Tu+rnMo9UQFESIk7C+6w4JIUVjbbrMjCqk0T6J86vMYWMX3+Eso2TORNJ6+UdcT5IcSQLF9KRrOE8SyRu/zkHLy1BqHW7vp6KCPz",
	"ConnectionId": "0b106475-ed26-4fb4-95e5-f8569f588010",
	"KeepAliveTimeout": 20.0,
	"DisconnectTimeout": 30.0,
	"ConnectionTimeout": 110.0,
	"TryWebSockets": false,
	"ProtocolVersion": "1.4",
	"TransportConnectTimeout": 5.0,
	"LongPollDelay": 0.0
}

**Comment by adamhartford** [comment] 2015-09-02 16:19
Can you put breakpoints in your server method. Make sure the call is reaching the server? Do you see outgoing traffic in Charles that indicates the `invoke` call. Also, I see you have this:

```csharp
Clients.Clients(connections.AllExcept(Context.ConnectionId)).getNewOnlineUser(user);
```

Are you testing with two devices? You won't get the callback on the device that calls `invoke` if you're broadcasting to every other client but the caller. Maybe use `Clients.All` just for testing?

I'm not sure how much help I'll be without access to your code. We did find one issue that I fixed in a recent commit (the number problem in the args array), but in general all of this works for me.

**Comment by pwr7549** [comment] 2015-09-02 16:26
Okay I can email you in private side instead of this with GitHub? 

Regards,
Patrick Reece

**Comment by adamhartford** [comment] 2015-09-02 16:27
I think you should add the SimpleHub example from the README to your server app, then use the SwiftR example iOS to verify that works, and work backwards from there.

**Comment by pwr7549** [comment] 2015-09-02 21:04
Hello Adam, 

I believe that I have found a reason of why we could not receive the response from the SignalR server unless we use the dynamic URL that jump us into another URL as from point A to point B. this app must start with “getSettings” of invoke server method in order to receive the new URL address from the server and then apply the next url address for the rest of new invoke server methods. The question is how I use this invoke server method’s callback for receiving the new URL address. 

This is old coding that last developer was working on it but never finish it nor get it working properly .. The developer used SignalR-ObjC for the iOS app.. 



[hub invoke:@"getSettings" withArgs:args completionHandler:^(id hubResult, NSError *error)
         {
             NSLog(@"Get Settings Results: %@", hubResult);
             // [connection stop];
             
             // [connection closed];
             
             //connection=nil;
             
             if (hubResult == nil)
             {
                 _dynamicfinalurl_forconnection=@"http://monkey.com/LPSignalRServer4/signalr/hubs”;  <<<<<<< Dynamicc Final URL  if hubResult is nil.. 
                 
             }
             else if ([hubResult isEqual:nil])
             {
                 _dynamicfinalurl_forconnection=@"http://monkey.com/LPSignalRServer4/signalr/hubs”;  <<<<<<< Dynamicc Final URL  if hubResult is nil.. 
                 
             }
             else if (hubResult ==[NSNull null])
             {
                 _dynamicfinalurl_forconnection=@“http://monkey.com/LPSignalRServer4/signalr/hubs”; <<<<<<< Dynamicc Final URL  if hubResult is nil.. 
             else
             {
                 NSLog(@"hubResultjoinmethod=%@",hubResult);
                 _dynamicfinalurl_forconnection=[NSString stringWithFormat:@"%@",[hubResult objectForKey:@"SignalRServerURL"]];  <<<<<<< Dynamicc Final URL is given by the server
                 _registration_url=[NSString stringWithFormat:@"%@",[hubResult objectForKey:@"RegistrationSiteURL"]];
                 //_dynamicfinalurl_forconnection=@"http://monkey.com:8080/LPSignalRServer4/signalr/hubs";
                 
                 
                 
             }
             __weak typeof(self) weakSelf = self;
             //connection.closed=^()
             {
                 NSLog(@"go into createsrconnection");
                 [weakSelf createsrconnection];
             };


How do I proof? 

I entered the URL on my Safari web browser, here it show below..  Please look at the bold prints at almost bottom of this page.. 

/*!
 * ASP.NET SignalR JavaScript Library v2.1.2
 * http://signalr.net/
 *
 * Copyright Microsoft Open Technologies, Inc. All rights reserved.
 * Licensed under the Apache 2.0
 * https://github.com/SignalR/SignalR/blob/master/LICENSE.md
 *
 */

/// <reference path="..\..\SignalR.Client.JS\Scripts\jquery-1.6.4.js" />
/// <reference path="jquery.signalR.js" />
(function ($, window, undefined) {
    /// <param name="$" type="jQuery" />
    "use strict";

    if (typeof ($.signalR) !== "function") {
        throw new Error("SignalR: SignalR is not loaded. Please ensure jquery.signalR-x.js is referenced before ~/signalr/js.");
    }

    var signalR = $.signalR;

    function makeProxyCallback(hub, callback) {
        return function () {
            // Call the client hub method
            callback.apply(hub, $.makeArray(arguments));
        };
    }

    function registerHubProxies(instance, shouldSubscribe) {
        var key, hub, memberKey, memberValue, subscriptionMethod;

        for (key in instance) {
            if (instance.hasOwnProperty(key)) {
                hub = instance[key];

                if (!(hub.hubName)) {
                    // Not a client hub
                    continue;
                }

                if (shouldSubscribe) {
                    // We want to subscribe to the hub events
                    subscriptionMethod = hub.on;
                } else {
                    // We want to unsubscribe from the hub events
                    subscriptionMethod = hub.off;
                }

                // Loop through all members on the hub and find client hub functions to subscribe/unsubscribe
                for (memberKey in hub.client) {
                    if (hub.client.hasOwnProperty(memberKey)) {
                        memberValue = hub.client[memberKey];

                        if (!$.isFunction(memberValue)) {
                            // Not a client hub function
                            continue;
                        }

                        subscriptionMethod.call(hub, memberKey, makeProxyCallback(hub, memberValue));
                    }
                }
            }
        }
    }

    $.hubConnection.prototype.createHubProxies = function () {
        var proxies = {};
        this.starting(function () {
            // Register the hub proxies as subscribed
            // (instance, shouldSubscribe)
            registerHubProxies(proxies, true);

            this._registerSubscribedHubs();
        }).disconnected(function () {
            // Unsubscribe all hub proxies when we "disconnect".  This is to ensure that we do not re-add functional call backs.
            // (instance, shouldSubscribe)
            registerHubProxies(proxies, false);
        });

        proxies['lPConfigServer'] = this.createHubProxy('lPConfigServer'); 
        proxies['lPConfigServer'].client = { };
        proxies['lPConfigServer'].server = {
            getSettings: function (versionName) {
                return proxies['lPConfigServer'].invoke.apply(proxies['lPConfigServer'], $.merge(["getSettings"], $.makeArray(arguments)));
             },

            getSignalRServerURL: function () {
                return proxies['lPConfigServer'].invoke.apply(proxies['lPConfigServer'], $.merge(["getSignalRServerURL"], $.makeArray(arguments)));
             },

            getSignalRServerURL2: function (versionName) {
                return proxies['lPConfigServer'].invoke.apply(proxies['lPConfigServer'], $.merge(["getSignalRServerURL2"], $.makeArray(arguments)));
             }
        };

        return proxies;
    };

    signalR.hub = $.hubConnection("/ConfigServer/signalr", { useDefaultPath: false });
    $.extend(signalR, signalR.hub.createHubProxies());

}(window.jQuery, window));

**Comment by adamhartford** [comment] 2015-10-09 13:01
Closing because I think I've done all I can to help with this one. We did find and fix an issue with passing numbers as arguments, but I think any further issue should be tracked separately.

**Closed by adamhartford** 2015-10-09 13:01 UTC
